### PR TITLE
Test resolution of a conflict

### PR DESCRIPTION
**Pull request by gaylordjohnson**
I've resolved a conflict where upstream and fork had made a change in readme on the same line. I synced upstream to my fork's local master > merge failed due to the above > I merged in fork's local master > pushed to fork's remote master > now PR to merge the merge back into upstream's master.
GLJ

### CODE REVIEW

**Comment by gaylordjohnson** [comment]
Oh, btw, I also learned how to do git diffs!
GLJ

**Comment by Blah0x1E6F** [comment]
Hey, could you make the code prettier? Maybe avoid using "<--->"
Blah

**Comment by gaylordjohnson** [comment]
Ok, made it prettier, check it out.
GLJ

**Comment by Blah0x1E6F** [comment]
Merged your pull request - congrats!
Blah

**Pull request merged**
